apiVersion: v1
kind: PersistentVolume
metadata:
  name: mumble-pv
  labels:
    type: local
spec:
  capacity:
    storage: "{{ .Values.mumble.size }}"
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "{{ .Values.mumble.hostpath }}"

