apiVersion: v1
kind: Service
metadata:
  name: voice-{{ .Values.nontld }}
spec:
  selector:
    name: mumble
  ports: 
  - name: mumble-tcp
    protocol: TCP
    port: 64738
    targetPort: 64738
  - name: mumble-udp
    protocol: UDP
    port: 64738
    targetPort: 64738

