{{- if eq .Values.internaltls "true" }}
apiVersion: v1
kind: Service
metadata:
  name: chat-{{ .Values.nontld }}
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx
{{- end }}
