{{- if eq .Values.internaltls "true" }}
apiVersion: v1
data:
  chat.conf: | 
    server {
      listen 80;
      server_name chat.{{ .Values.domain }};
      rewrite ^ https://$host$request_uri permanent;
    }
    server {
      listen 443 ssl;
      server_name chat.{{ .Values.domain }};
      ssl_certificate /opt/fullchain.pem;
      ssl_certificate_key /opt/privkey.pem;
      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
      ssl_prefer_server_ciphers on;
      location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://chat-backend-{{ .Values.nontld }};
        proxy_read_timeout 90;
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-chat-config
{{- end }}
