apiVersion: v1
kind: PersistentVolume
metadata:
  name: mm-pv
  labels:
    type: local
spec:
  capacity:
    storage: "{{ .Values.mattermost.mmsize }}"
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "{{ .Values.mattermost.mmhostpath }}"

