apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mm-pvc
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  volumeName: mm-pv
  resources:
    requests:
      storage: "{{ .Values.mattermost.mmsize }}"

