apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mpgdata-pvc
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  volumeName: mpgdata-pv
  resources:
    requests:
      storage: "{{ .Values.mattermost.pgsize }}"

