apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mpg
spec:
  template:
    metadata:
      name: mpg
      labels:
        name: mpg
    spec:
      volumes:
        - name: mpgdata
          persistentVolumeClaim:
            claimName: mpgdata-pvc
      containers:
      - name: mpg
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.mattermost.pgpass }}"
        - name: POSTGRES_DB
          value: "mattermost"
        - name: POSTGRES_USER
          value: "mmuser"
        volumeMounts:
        - name: mpgdata
          mountPath: "/var/lib/postgresql/data/"
        imagePullPolicy: IfNotPresent
  replicas: 1
  selector:
    matchLabels:
      name: mpg

