apiVersion: v1
kind: PersistentVolume
metadata:
  name: vpndata
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "{{ .Values.vpn.hostpath }}"

