apiVersion: v1
kind: Service
metadata:
  name: vpnout-{{ .Values.nontld }}
spec:
  selector:
    name: openvpn
  type: NodePort
  ports: 
  - name: ovpnudp
    protocol: UDP
    port: 1194
    targetPort: 1194
    nodePort: 1194
