apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: g-pvc
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  volumeName: g-pv
  resources:
    requests:
      storage: "{{ .Values.gitea.gsize }}"

