apiVersion: v1
kind: PersistentVolume
metadata:
  name: g-pv
  labels:
    type: local
spec:
  capacity:
    storage: "{{ .Values.gitea.gsize }}"
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "{{ .Values.gitea.ghostpath }}"

