apiVersion: v1
kind: PersistentVolume
metadata:
  name: gpgdata-pv
  labels:
    type: local
spec:
  capacity:
    storage: "{{ .Values.gitea.pgsize }}"
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "{{ .Values.gitea.pghostpath }}"

