apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpgdata-pvc
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  volumeName: gpgdata-pv
  resources:
    requests:
      storage: "{{ .Values.gitea.pgsize }}"

